version: '3.7'

services:
    pocketbase:
        image: ghcr.io/muchobien/pocketbase:latest
        container_name: pocketbase
        restart: unless-stopped
        environment:
            ENCRYPTION: example #optional
        ports:
            - '8090:8090'
        volumes:
            - pb_data:/pb/pb_data
        healthcheck:
            #optional (recommended) since v0.10.0
            test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    pb_data:
